name: Dev Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install in editable mode
        run: |
          python -m pip install -U pip
          pip install -e .

      - name: Run CLI (optional smoke test)
        run: |
          fueltrack --help
